version: '3.1'

services: 

  db:

    image: mysql

    restart: always

    environment: 
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      - 3308:3306



  phpmyadmin:
    
    image: phpmyadmin

    restart: always

    ports:
      - 8081:80


  server:

    depends_on: 
      - db

    restart: always

    build: .

    ports:
      - 3000:3000

volumes: 
  db:
